"""Initial tables

Revision ID: 7a70395f71e9
Revises: 
Create Date: 2024-11-16 16:45:04.399111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a70395f71e9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spy_cat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('years_of_experience', sa.Integer(), nullable=False),
    sa.Column('breed', sa.String(length=30), nullable=False),
    sa.Column('salary', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('executor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['executor_id'], ['spy_cat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('target',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mission_id'], ['mission.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('target')
    op.drop_table('mission')
    op.drop_table('spy_cat')
    # ### end Alembic commands ###
